# Generated by Django 2.0.3 on 2018-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_models', '0002_calendarweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarweek',
            name='week',
            field=models.CharField(max_length=10, null=True, verbose_name='calendar week'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(help_text='jahr', max_length=4, null=True, verbose_name='year'),
        ),
    ]
