# Generated by Django 2.0.3 on 2018-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_models', '0005_auto_20180513_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=2, null=True, verbose_name='quarter')),
            ],
        ),
    ]
