# Generated by Django 2.0.3 on 2018-05-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_models', '0006_quarters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarweek',
            old_name='week',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quarters',
            old_name='quarter',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='name',
        ),
    ]
