# Generated by Django 2.0.3 on 2018-05-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_development', '0006_auto_20180515_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdevelopment',
            options={'verbose_name': ('Project development',), 'verbose_name_plural': ('Project developments',)},
        ),
    ]
