# Generated by Django 2.0.3 on 2018-05-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0008_auto_20180516_1302'),
        ('project_development', '0007_auto_20180516_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdevelopment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projectdevelopment',
            unique_together={('project', 'project_status', 'project_tendency')},
        ),
    ]
