# Generated by Django 2.0.3 on 2018-05-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_development', '0008_auto_20180516_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectdevelopment',
            unique_together=set(),
        ),
    ]
