# Generated by Django 2.0.3 on 2018-05-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProposalDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ControlCycleDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalSignificanceDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCharacterDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Namen', max_length=50, unique=True, verbose_name='project name')),
                ('strategic_importance', models.IntegerField(blank=True, help_text='Strategische Bedeutung', verbose_name='strategic importance')),
                ('operational_urgency', models.IntegerField(blank=True, help_text='Operative Dringlichkeit', verbose_name='operational urgency')),
                ('project_goal', models.CharField(blank=True, help_text='Projektziel', max_length=100, verbose_name='project goal')),
                ('project_handbook_file', models.FileField(blank=True, help_text='handbuch datai', null=True, upload_to='', verbose_name='handbook file')),
                ('e3_number', models.CharField(blank=True, help_text='E3-Nummer', max_length=20, verbose_name='e 3number')),
                ('business_category', models.IntegerField(blank=True, help_text='Geschäftskategorie', null=True, verbose_name='business category')),
                ('service_nature', models.IntegerField(blank=True, help_text='Leistungsart', null=True, verbose_name='service nature')),
                ('invoiceability', models.IntegerField(blank=True, help_text='Verrechenbarkeit', null=True, verbose_name='invoicability')),
                ('business_number', models.CharField(blank=True, help_text='Geschäftsnummer', max_length=20, verbose_name='business')),
                ('comment', models.TextField(blank=True, help_text='Bemerkung', max_length=200, verbose_name='comment')),
                ('business_proposal', models.ForeignKey(blank=True, help_text='Geschäftsantrag', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.BusinessProposalDropdown', verbose_name='business proposal')),
                ('control_cycle', models.ForeignKey(blank=True, help_text='Steuerungszyklus (L)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ControlCycleDropdown', verbose_name='control cycle')),
                ('political_significance', models.ForeignKey(blank=True, help_text='Politische Bedeutung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.PoliticalSignificanceDropdown', verbose_name='political significance')),
                ('project_character', models.ForeignKey(blank=True, help_text='Projektcharakter (Projektbezogen)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectCharacterDropdown', verbose_name='project character')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHandbookDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNatureDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPriorityDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusPhaseDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTypeDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='RadarPortfolioDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessmentDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_handbook',
            field=models.ForeignKey(blank=True, help_text='Projekthandbuch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectHandbookDropdown', verbose_name='project handbook'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_nature',
            field=models.ForeignKey(blank=True, help_text='Projekttart', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectNatureDropdown', verbose_name='project nature'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_priority',
            field=models.ForeignKey(blank=True, help_text='Projektpriorität (L)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectPriorityDropdown', verbose_name='project priority'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_status_phase',
            field=models.ForeignKey(blank=True, help_text='Projektstatus/Projektphase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectStatusPhaseDropdown', verbose_name='project status or phase'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_type',
            field=models.ForeignKey(blank=True, help_text='Projekttyp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectTypeDropdown', verbose_name='project type'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='radar_portfolio',
            field=models.ForeignKey(blank=True, help_text='Radar oder Projektportfolio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.RadarPortfolioDropdown', verbose_name='radar or portfolio'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Projekt-Risikobeurteilung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.RiskAssessmentDropdown', verbose_name='risk assessment'),
        ),
    ]
