# Generated by Django 2.0.3 on 2018-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='business_number',
            field=models.CharField(blank=True, help_text='Geschäftsnummer', max_length=20, null=True, verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='comment',
            field=models.TextField(blank=True, help_text='Bemerkung', max_length=200, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='e3_number',
            field=models.CharField(blank=True, help_text='E3-Nummer', max_length=20, null=True, verbose_name='e 3number'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='operational_urgency',
            field=models.IntegerField(blank=True, help_text='Operative Dringlichkeit', null=True, verbose_name='operational urgency'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_goal',
            field=models.CharField(blank=True, help_text='Projektziel', max_length=100, null=True, verbose_name='project goal'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='strategic_importance',
            field=models.IntegerField(blank=True, help_text='Strategische Bedeutung', null=True, verbose_name='strategic importance'),
        ),
    ]
