# Generated by Django 2.0.3 on 2018-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0002_auto_20180510_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='business_number',
            field=models.CharField(blank=True, help_text='Geschäftsnummer', max_length=20, null=True, verbose_name='business number'),
        ),
    ]
