# Generated by Django 2.0.3 on 2018-05-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0005_auto_20180515_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='business_proposal',
            field=models.ForeignKey(blank=True, help_text='Geschäftsantrag', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.BusinessProposalDropdown', verbose_name='business proposal'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_nature',
            field=models.ForeignKey(blank=True, help_text='Projekttart', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectNatureDropdown', verbose_name='project nature'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_type',
            field=models.ForeignKey(blank=True, help_text='Projekttyp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectTypeDropdown', verbose_name='project type'),
        ),
    ]
