# Generated by Django 2.0.3 on 2018-05-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0006_auto_20180515_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdata',
            options={'verbose_name': ('Project data',), 'verbose_name_plural': ('Project Data',)},
        ),
    ]
