# Generated by Django 2.0.3 on 2018-05-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0007_auto_20180516_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdata',
            options={},
        ),
    ]
