# Generated by Django 2.0.3 on 2018-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0008_auto_20180516_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdata',
            options={'verbose_name_plural': 'Project data'},
        ),
    ]
