# Generated by Django 2.0.3 on 2018-05-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='abreviation',
        ),
    ]
