# Generated by Django 2.0.3 on 2018-05-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180521_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='abreviation',
        ),
    ]
