# Generated by Django 2.0.3 on 2018-05-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionManagementDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='IlustratorDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='LeadingRoleDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='LeadingTeamDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='OverallPMTeamDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PlannerControlDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PMDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communications', models.ForeignKey(blank=True, help_text='Kommunikation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.CommunicationsDropdown', verbose_name='communications')),
                ('construction_management', models.ForeignKey(blank=True, help_text='Bauleitung (Baubegleitung)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.ConstructionManagementDropdown', verbose_name='construction management')),
                ('illustrator', models.ForeignKey(blank=True, help_text='ZeichnerIn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.IlustratorDropdown', verbose_name='illustrator')),
                ('leading_role', models.ForeignKey(blank=True, help_text='Federführende Stelle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.LeadingRoleDropdown', verbose_name='leading role')),
                ('leading_team', models.ForeignKey(blank=True, help_text='Federführende Fachgruppe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.LeadingTeamDropdown', verbose_name='leading team')),
                ('overall_pm_team', models.ForeignKey(blank=True, help_text='Gesamtprojektleitung (Koordinationsteam)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.OverallPMTeamDropdown', verbose_name='overall pm team')),
                ('planner_control', models.ForeignKey(blank=True, help_text='Planerleistung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.PlannerControlDropdown', verbose_name='planner control')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectData', verbose_name='project assignment')),
                ('project_management', models.ForeignKey(blank=True, help_text='Projektleitung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignment', to=settings.AUTH_USER_MODEL, verbose_name='project management')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResponsibilityDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_responsibility',
            field=models.ForeignKey(blank=True, help_text='Projektverantwortung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.ProjectResponsibilityDropdown', verbose_name='project responsibility'),
        ),
    ]
