# Generated by Django 2.0.3 on 2018-05-10 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='project_management',
            field=models.ForeignKey(blank=True, help_text='Projektleitung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignment', to=settings.AUTH_USER_MODEL, verbose_name='project management'),
        ),
    ]
