# Generated by Django 2.0.3 on 2018-05-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0003_auto_20180510_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='project_management',
            field=models.ForeignKey(blank=True, help_text='Projektleitung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_assignment.PMDropdown', verbose_name='project management'),
        ),
    ]
