# Generated by Django 2.0.3 on 2018-05-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0005_auto_20180510_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IlustratorDropdown',
            new_name='IllustratorDropdown',
        ),
    ]
