# Generated by Django 2.0.3 on 2018-05-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0007_auto_20180513_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignment', to='project_data.ProjectData', verbose_name='project name'),
        ),
    ]
