# Generated by Django 2.0.3 on 2018-05-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_assignment', '0009_auto_20180515_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_management',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_management',
            field=models.ForeignKey(help_text='Projektleitung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignment', to=settings.AUTH_USER_MODEL, verbose_name='project management'),
        ),
    ]
