# Generated by Django 2.0.3 on 2018-05-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0010_auto_20180515_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PMDropdown',
        ),
    ]
