# Generated by Django 2.0.3 on 2018-05-16 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_assignment', '0011_delete_pmdropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_management',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_management',
            field=models.ManyToManyField(help_text='Projektleitung', related_name='project_assignments', to=settings.AUTH_USER_MODEL, verbose_name='project management'),
        ),
    ]
