# Generated by Django 2.0.3 on 2018-05-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaendarWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10, verbose_name='calendar week')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_factors', models.TextField(blank=True, help_text='Einfluss externe Faktoren', null=True, verbose_name='external factors')),
                ('communications', models.TextField(blank=True, help_text='Kommunicaton', null=True, verbose_name='communications')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationsDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionManagementDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CreditStatusDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='FinancingDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='IlustratorDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='LeadingRoleDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='LeadingTeamDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='milestone dropdown value')),
            ],
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.ForeignKey(blank=True, help_text='Kommentare', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.CommentaryOptions', verbose_name='commentary')),
                ('milestone_calendar_week', models.ForeignKey(blank=True, help_text='Meilenstein Kalenderwocke', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ClaendarWeek', verbose_name='milestone calendar week')),
                ('milestone_value', models.ForeignKey(blank=True, help_text='Meilstein Inhalt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.MilestoneDropdown', verbose_name='milestone value')),
            ],
        ),
        migrations.CreateModel(
            name='OverallPMTeamDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PlannerControlDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PMDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communications', models.ForeignKey(blank=True, help_text='Kommunikation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.CommunicationsDropdown', verbose_name='communications')),
                ('construction_management', models.ForeignKey(blank=True, help_text='Bauleitung (Baubegleitung)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ConstructionManagementDropdown', verbose_name='construction management')),
                ('illustrator', models.ForeignKey(blank=True, help_text='ZeichnerIn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.IlustratorDropdown', verbose_name='illustrator')),
                ('leading_role', models.ForeignKey(blank=True, help_text='Federführende Stelle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.LeadingRoleDropdown', verbose_name='leading role')),
                ('leading_team', models.ForeignKey(blank=True, help_text='Federführende Fachgruppe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.LeadingTeamDropdown', verbose_name='leading team')),
                ('overall_pm_team', models.ForeignKey(blank=True, help_text='Gesamtprojektleitung (Koordinationsteam)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.OverallPMTeamDropdown', verbose_name='overall pm team')),
                ('planner_control', models.ForeignKey(blank=True, help_text='Planerleistung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.PlannerControlDropdown', verbose_name='planner control')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDependencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_dependencies', models.TextField(blank=True, help_text='Abhängigkeiten Inhaltlich', null=True, verbose_name='content dependencies')),
                ('time_dependencies', models.TextField(blank=True, help_text='Abhängigkeiten Zeitlich', null=True, verbose_name='time dependencies')),
                ('capacity_dependencies', models.TextField(blank=True, help_text='Abhängigkeiten Kapazitativ', null=True, verbose_name='capacity dependencies')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_number', models.CharField(blank=True, help_text='Investitions-Nr.', max_length=20, verbose_name='investment number')),
                ('loan_budget', models.IntegerField(blank=True, help_text='Kredit- /Budgetsumme', verbose_name='loan budget')),
                ('third_party_contributions', models.IntegerField(blank=True, help_text='Beiträge Dritter', verbose_name='third party contributions')),
                ('net_expense_previous_years', models.IntegerField(blank=True, help_text='Netto-Ausgaben Vorjahre', verbose_name='net expense previous years')),
                ('remaining_credit_current_year', models.IntegerField(blank=True, help_text='Kreditrest per 1.1. aktuelles Jahr', verbose_name='remaining credit current year')),
                ('spending_current_year', models.IntegerField(blank=True, help_text='Ist Ausgaben aktuelles Jahr', verbose_name='spending current year')),
                ('forecast_current_year', models.IntegerField(blank=True, help_text='Prognose laufendes Jahr', verbose_name='forecast current year')),
                ('remaining_credit_following_year', models.IntegerField(blank=True, help_text='Kreditrest per 1.1. folgendes Jahr', verbose_name='remaining credit following year')),
                ('VAT_following_year', models.IntegerField(blank=True, help_text='Mehrwertabschöpfung folgendes Jahr', verbose_name='VAT following year')),
                ('forecast_following_year', models.IntegerField(blank=True, help_text='Prognose folgendes Jahr', verbose_name='forecast following year')),
                ('VAT_further_years', models.IntegerField(blank=True, help_text='Mehrwertabschöpfung weitere Jahre', verbose_name='VAT following year')),
                ('forecast_further_years', models.IntegerField(blank=True, help_text='Prognose weitere Jahre', verbose_name='forecast further years')),
                ('credit_status', models.ForeignKey(blank=True, help_text='Status Projektkredit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.CreditStatusDropdown', verbose_name='credit status')),
                ('financing', models.ForeignKey(blank=True, help_text='Finanzierungsart / MIP Rubrik', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.FinancingDropdown', verbose_name='financing')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResponsibilityDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='status value')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTendencyDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='tendency value')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='Quartal', max_length=20, verbose_name='quarter')),
                ('project_phase', models.IntegerField(blank=True, help_text='Phase', verbose_name='project phase')),
                ('project_responsibility', models.IntegerField(blank=True, help_text='Projektverantwortung', verbose_name='project responsibility')),
                ('overall_pm_team_allocation', models.IntegerField(blank=True, help_text='Gesamtprojektleitung', verbose_name='overall pm team allocation')),
                ('project_management_allocation', models.IntegerField(blank=True, help_text='Projektleitung', verbose_name='project management allocation')),
                ('planner_control_allocation', models.IntegerField(blank=True, help_text='Planerleistung', verbose_name='planner control allocation')),
                ('construction_management_allocation', models.IntegerField(blank=True, help_text='Bauleitung', verbose_name='construction management allocation')),
                ('illustrator_allocation', models.IntegerField(blank=True, help_text='ZeichnerIn', verbose_name='illustrator allocation')),
                ('supplementary_construction_management_allocation', models.IntegerField(blank=True, help_text='Bauleitung (Baubegleitung)', verbose_name='supplementary construction management allocation')),
                ('communications_allocation', models.IntegerField(blank=True, help_text='Kommunikation', verbose_name='communications allocation')),
                ('total_allocation', models.IntegerField(blank=True, help_text='Total Aufwand', verbose_name='total allocation')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsAssessmentDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='TendenciesDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='tendencies dropdown value')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='jahr', max_length=4, verbose_name='year')),
            ],
        ),
        migrations.AddField(
            model_name='projectdata',
            name='business_category',
            field=models.IntegerField(blank=True, help_text='Geschäftskategorie', null=True, verbose_name='business category'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='business_number',
            field=models.CharField(blank=True, help_text='Geschäftsnummer', max_length=20, verbose_name='business'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='comment',
            field=models.TextField(blank=True, help_text='Bemerkung', max_length=200, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='control_cycle',
            field=models.ForeignKey(blank=True, help_text='Steuerungszyklus (L)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ControlCycleDropdown', verbose_name='control cycle'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='e3_number',
            field=models.CharField(blank=True, help_text='E3-Nummer', max_length=20, verbose_name='e 3number'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='invoiceability',
            field=models.IntegerField(blank=True, help_text='Verrechenbarkeit', null=True, verbose_name='invoicability'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_character',
            field=models.ForeignKey(blank=True, help_text='Projektcharakter (Projektbezogen)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectCharacterDropdown', verbose_name='project character'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_goal',
            field=models.CharField(blank=True, help_text='Projektziel', max_length=100, verbose_name='project goal'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_handbook',
            field=models.ForeignKey(blank=True, help_text='Projekthandbuch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectHandbookDropdown', verbose_name='project handbook'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_handbook_file',
            field=models.FileField(blank=True, help_text='handbuch datai', null=True, upload_to='', verbose_name='handbook file'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project_status_phase',
            field=models.ForeignKey(blank=True, help_text='Projektstatus/Projektphase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectStatusPhaseDropdown', verbose_name='project status or phase'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='Projekt-Risikobeurteilung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.RiskAssessmentDropdown', verbose_name='risk assessment'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='service_nature',
            field=models.IntegerField(blank=True, help_text='Leistungsart', null=True, verbose_name='service nature'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='business_proposal',
            field=models.ForeignKey(blank=True, help_text='Geschäftsantrag', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.BusinessProposalDropdown', verbose_name='business proposal'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='name',
            field=models.CharField(help_text='Project Namen', max_length=50, unique=True, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='operational_urgency',
            field=models.IntegerField(blank=True, help_text='Operative Dringlichkeit', verbose_name='operational urgency'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='political_significance',
            field=models.ForeignKey(blank=True, help_text='Politische Bedeutung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.PoliticalSignificanceDropdown', verbose_name='political significance'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_nature',
            field=models.ForeignKey(blank=True, help_text='Projekttart', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectNatureDropdown', verbose_name='project nature'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_priority',
            field=models.ForeignKey(blank=True, help_text='Projektpriorität (L)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectPriorityDropdown', verbose_name='project priority'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_type',
            field=models.ForeignKey(blank=True, help_text='Projekttyp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectTypeDropdown', verbose_name='project type'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='radar_portfolio',
            field=models.ForeignKey(blank=True, help_text='Radar oder Projektportfolio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.RadarPortfolioDropdown', verbose_name='radar or portfolio'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='strategic_importance',
            field=models.IntegerField(blank=True, help_text='Strategische Bedeutung', verbose_name='strategic importance'),
        ),
        migrations.AddField(
            model_name='quarterlydetails',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Jahr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.Year', verbose_name='year'),
        ),
        migrations.AddField(
            model_name='projectfinances',
            name='project',
            field=models.ForeignKey(on_delete='models.SET_NULL', to='pm_tool.ProjectData', verbose_name='project assignment'),
        ),
        migrations.AddField(
            model_name='projectfinances',
            name='requirements_assessment',
            field=models.ForeignKey(blank=True, help_text='Bedürfnisabklärung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.RequirementsAssessmentDropdown', verbose_name='requirements assessment'),
        ),
        migrations.AddField(
            model_name='projectdevelopment',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectStatusDropdown', verbose_name='project status'),
        ),
        migrations.AddField(
            model_name='projectdevelopment',
            name='project_tendency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectTendencyDropdown', verbose_name='project tendency'),
        ),
        migrations.AddField(
            model_name='projectdependencies',
            name='project',
            field=models.ForeignKey(on_delete='models.SET_NULL', to='pm_tool.ProjectData', verbose_name='project assignment'),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(on_delete='models.SET_NULL', to='pm_tool.ProjectData', verbose_name='project assignment'),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_management',
            field=models.ForeignKey(blank=True, help_text='Projektleitung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.PMDropdown', verbose_name='project management'),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_responsibility',
            field=models.ForeignKey(blank=True, help_text='Projektverantwortung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectResponsibilityDropdown', verbose_name='project responsibility'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='project',
            field=models.ForeignKey(on_delete='models.SET_NULL', to='pm_tool.ProjectData', verbose_name='project assignment'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='quarterly_details',
            field=models.ForeignKey(blank=True, help_text='Projektablauf & Ressourcenplanung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.QuarterlyDetails', verbose_name='quarterly details'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.ProjectData', verbose_name='project assignment'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='tendency',
            field=models.ForeignKey(blank=True, help_text='Tendenz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.TendenciesDropdown', verbose_name='tendency'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Jahr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm_tool.Year', verbose_name='year'),
        ),
    ]
