# Generated by Django 2.0.3 on 2018-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_dependencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdependencies',
            name='project',
            field=models.ForeignKey(on_delete='models.SET_NULL', to='project_data.ProjectData', verbose_name='project name'),
        ),
    ]
