# Generated by Django 2.0.3 on 2018-05-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_dependencies', '0003_auto_20180511_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdependencies',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_dependencies', to='project_data.ProjectData', verbose_name='project name'),
        ),
    ]
