# Generated by Django 2.0.3 on 2018-05-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_dependencies', '0004_auto_20180513_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdependencies',
            options={'verbose_name': ('Project dependencies',), 'verbose_name_plural': ('Project dependencies',)},
        ),
    ]
