# Generated by Django 2.0.3 on 2018-05-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_dependencies', '0005_auto_20180516_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdependencies',
            options={},
        ),
    ]
