# Generated by Django 2.0.3 on 2018-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_dependencies', '0006_auto_20180516_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdependencies',
            options={'verbose_name_plural': 'Project dependencies'},
        ),
    ]
