# Generated by Django 2.0.3 on 2018-05-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_data', '0001_initial'),
        ('helper_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_factors', models.TextField(blank=True, help_text='Einfluss externe Faktoren', null=True, verbose_name='external factors')),
                ('communications', models.TextField(blank=True, help_text='Kommunicaton', null=True, verbose_name='communications')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='milestone dropdown value')),
            ],
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.ForeignKey(blank=True, help_text='Kommentare', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_milestones.CommentaryOptions', verbose_name='commentary')),
                ('milestone_calendar_week', models.ForeignKey(blank=True, help_text='Meilenstein Kalenderwocke', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_models.CalendarWeek', verbose_name='milestone calendar week')),
                ('milestone_value', models.ForeignKey(blank=True, help_text='Meilstein Inhalt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_milestones.MilestoneDropdown', verbose_name='milestone value')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectData', verbose_name='project assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TendenciesDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='tendencies dropdown value')),
            ],
        ),
        migrations.AddField(
            model_name='milestones',
            name='tendency',
            field=models.ForeignKey(blank=True, help_text='Tendenz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_milestones.TendenciesDropdown', verbose_name='tendency'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Jahr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_models.Year', verbose_name='year'),
        ),
    ]
