# Generated by Django 2.0.3 on 2018-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_milestones', '0002_auto_20180509_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestones',
            options={'verbose_name_plural': 'milestones'},
        ),
        migrations.AlterField(
            model_name='milestonedropdown',
            name='value',
            field=models.CharField(max_length=100, verbose_name='milestone dropdown value'),
        ),
    ]
