# Generated by Django 2.0.3 on 2018-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_milestones', '0004_auto_20180510_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaryoptions',
            name='heading',
            field=models.CharField(help_text='Kommentar Title', max_length=50, null=True, verbose_name='commentary heading'),
        ),
    ]
