# Generated by Django 2.0.3 on 2018-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_milestones', '0005_auto_20180510_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonedropdown',
            name='value',
            field=models.CharField(max_length=100, null=True, verbose_name='milestone dropdown value'),
        ),
        migrations.AlterField(
            model_name='tendenciesdropdown',
            name='value',
            field=models.CharField(max_length=20, null=True, verbose_name='tendencies dropdown value'),
        ),
    ]
