# Generated by Django 2.0.3 on 2018-05-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_milestones', '0007_auto_20180513_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestonedropdown',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tendenciesdropdown',
            old_name='value',
            new_name='name',
        ),
    ]
