# Generated by Django 2.0.3 on 2018-05-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_models', '0007_auto_20180515_0911'),
        ('project_data', '0005_auto_20180515_0948'),
        ('project_milestones', '0008_auto_20180515_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='milestone_calendar_week',
            field=models.ForeignKey(blank=True, help_text='Meilenstein Kalenderwocke', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_models.CalendarWeek', verbose_name='milestone_calendar_week'),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='milestone_value',
            field=models.ForeignKey(blank=True, help_text='Meilstein Inhalt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_milestones.MilestoneDropdown', verbose_name='milestone_value'),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_milestones', to='project_data.ProjectData', verbose_name='project_name'),
        ),
        migrations.AlterUniqueTogether(
            name='milestones',
            unique_together={('project', 'year', 'milestone_calendar_week')},
        ),
    ]
