# Generated by Django 2.0.3 on 2018-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_milestones', '0010_auto_20180515_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestones',
            name='commentary',
        ),
        migrations.AddField(
            model_name='milestones',
            name='communications',
            field=models.TextField(blank=True, help_text='Kommunicaton', null=True, verbose_name='communications'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='external_factors',
            field=models.TextField(blank=True, help_text='Einfluss externe Faktoren', null=True, verbose_name='external factors'),
        ),
        migrations.DeleteModel(
            name='CommentaryOptions',
        ),
    ]
