# Generated by Django 2.0.3 on 2018-05-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_milestones', '0011_auto_20180516_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestones',
            options={'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
    ]
