# Generated by Django 2.0.3 on 2018-05-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_milestones', '0012_auto_20180516_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestones',
            options={'ordering': ['year', 'milestone_calendar_week'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
    ]
