# Generated by Django 2.0.3 on 2018-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_finances', '0002_auto_20180510_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinances',
            name='VAT_following_year',
            field=models.IntegerField(blank=True, help_text='Mehrwertabschöpfung folgendes Jahr', null=True, verbose_name='VAT following year'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='VAT_further_years',
            field=models.IntegerField(blank=True, help_text='Mehrwertabschöpfung weitere Jahre', null=True, verbose_name='VAT following year'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='forecast_current_year',
            field=models.IntegerField(blank=True, help_text='Prognose laufendes Jahr', null=True, verbose_name='forecast current year'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='forecast_following_year',
            field=models.IntegerField(blank=True, help_text='Prognose folgendes Jahr', null=True, verbose_name='forecast following year'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='forecast_further_years',
            field=models.IntegerField(blank=True, help_text='Prognose weitere Jahre', null=True, verbose_name='forecast further years'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='investment_number',
            field=models.CharField(blank=True, help_text='Investitions-Nr.', max_length=20, null=True, verbose_name='investment number'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='loan_budget',
            field=models.IntegerField(blank=True, help_text='Kredit- /Budgetsumme', null=True, verbose_name='loan budget'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='net_expense_previous_years',
            field=models.IntegerField(blank=True, help_text='Netto-Ausgaben Vorjahre', null=True, verbose_name='net expense previous years'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='project',
            field=models.ForeignKey(null=True, on_delete='models.SET_NULL', to='project_data.ProjectData', verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='remaining_credit_current_year',
            field=models.IntegerField(blank=True, help_text='Kreditrest per 1.1. aktuelles Jahr', null=True, verbose_name='remaining credit current year'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='remaining_credit_following_year',
            field=models.IntegerField(blank=True, help_text='Kreditrest per 1.1. folgendes Jahr', null=True, verbose_name='remaining credit following year'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='spending_current_year',
            field=models.IntegerField(blank=True, help_text='Ist Ausgaben aktuelles Jahr', null=True, verbose_name='spending current year'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='third_party_contributions',
            field=models.IntegerField(blank=True, help_text='Beiträge Dritter', null=True, verbose_name='third party contributions'),
        ),
    ]
