# Generated by Django 2.0.3 on 2018-05-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_models', '0002_calendarweek'),
        ('project_finances', '0003_auto_20180510_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAT', models.IntegerField(blank=True, help_text='Mehrwertabschöpfung', null=True, verbose_name='VAT')),
                ('forecast_further_years', models.IntegerField(blank=True, help_text='Prognose', null=True, verbose_name='forecast')),
                ('year', models.ForeignKey(blank=True, help_text='Jahr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_models.Year', verbose_name='year')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='VAT_following_year',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='VAT_further_years',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='forecast_following_year',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='forecast_further_years',
        ),
        migrations.AddField(
            model_name='projectfinances',
            name='yearly_forecasts',
            field=models.ForeignKey(blank=True, help_text='Prognosen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_finances.YearlyForecast', verbose_name='yearly forecasts'),
        ),
    ]
