# Generated by Django 2.0.3 on 2018-05-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_finances', '0004_auto_20180510_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstatusdropdown',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='financingdropdown',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='projectfinances',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectData', verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='requirementsassessmentdropdown',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
    ]
