# Generated by Django 2.0.3 on 2018-05-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0004_auto_20180511_2025'),
        ('project_finances', '0005_auto_20180511_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyforecast',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_data.ProjectData', verbose_name='project name'),
        ),
    ]
