# Generated by Django 2.0.3 on 2018-05-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_finances', '0007_auto_20180513_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinances',
            name='yearly_forecasts',
        ),
        migrations.RemoveField(
            model_name='yearlyforecast',
            name='project',
        ),
        migrations.AddField(
            model_name='yearlyforecast',
            name='project_finance',
            field=models.ForeignKey(blank=True, help_text='Prognosen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_forecasts', to='project_finances.ProjectFinances', verbose_name='project finance'),
        ),
    ]
