# Generated by Django 2.0.3 on 2018-05-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_models', '0007_auto_20180515_0911'),
        ('project_finances', '0009_auto_20180514_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyforecast',
            name='project_finance',
            field=models.ForeignKey(help_text='Prognosen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_forecasts', to='project_finances.ProjectFinances', verbose_name='project_finance'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlyforecast',
            unique_together={('project_finance', 'year')},
        ),
    ]
