# Generated by Django 2.0.3 on 2018-05-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_finances', '0010_auto_20180515_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlyforecast',
            options={'verbose_name': 'Yearly forecast', 'verbose_name_plural': 'Yearly forecasts'},
        ),
        migrations.AlterField(
            model_name='yearlyforecast',
            name='project_finance',
            field=models.ForeignKey(help_text='Prognosen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_forecasts', to='project_finances.ProjectFinances', verbose_name='project finance'),
        ),
    ]
