# Generated by Django 2.0.3 on 2018-05-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_finances', '0011_auto_20180515_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinances',
            name='forecast_current_year',
        ),
        migrations.AddField(
            model_name='projectfinances',
            name='forecasts',
            field=models.ForeignKey(blank=True, help_text='Prognosen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_finances.YearlyForecast', verbose_name='forecasts'),
        ),
    ]
