# Generated by Django 2.0.3 on 2018-05-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_finances', '0012_auto_20180515_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinances',
            name='forecasts',
        ),
    ]
