# Generated by Django 2.0.3 on 2018-05-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_finances', '0014_auto_20180515_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlyforecast',
            options={'ordering': ['year'], 'verbose_name': 'Yearly forecast', 'verbose_name_plural': 'Yearly forecasts'},
        ),
    ]
