# Generated by Django 2.0.3 on 2018-05-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper_models', '0001_initial'),
        ('project_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete='models.SET_NULL', to='project_data.ProjectData', verbose_name='project assignment')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='Quartal', max_length=20, verbose_name='quarter')),
                ('project_phase', models.IntegerField(blank=True, help_text='Phase', verbose_name='project phase')),
                ('project_responsibility', models.IntegerField(blank=True, help_text='Projektverantwortung', verbose_name='project responsibility')),
                ('overall_pm_team_allocation', models.IntegerField(blank=True, help_text='Gesamtprojektleitung', verbose_name='overall pm team allocation')),
                ('project_management_allocation', models.IntegerField(blank=True, help_text='Projektleitung', verbose_name='project management allocation')),
                ('planner_control_allocation', models.IntegerField(blank=True, help_text='Planerleistung', verbose_name='planner control allocation')),
                ('construction_management_allocation', models.IntegerField(blank=True, help_text='Bauleitung', verbose_name='construction management allocation')),
                ('illustrator_allocation', models.IntegerField(blank=True, help_text='ZeichnerIn', verbose_name='illustrator allocation')),
                ('supplementary_construction_management_allocation', models.IntegerField(blank=True, help_text='Bauleitung (Baubegleitung)', verbose_name='supplementary construction management allocation')),
                ('communications_allocation', models.IntegerField(blank=True, help_text='Kommunikation', verbose_name='communications allocation')),
                ('total_allocation', models.IntegerField(blank=True, help_text='Total Aufwand', verbose_name='total allocation')),
                ('year', models.ForeignKey(blank=True, help_text='Jahr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_models.Year', verbose_name='year')),
            ],
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='quarterly_details',
            field=models.ForeignKey(blank=True, help_text='Projektablauf & Ressourcenplanung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_allocation.QuarterlyDetails', verbose_name='quarterly details'),
        ),
    ]
