# Generated by Django 2.0.3 on 2018-05-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_models', '0002_calendarweek'),
        ('project_allocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterlydetails',
            name='year',
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='quarterly_details',
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='communications_allocation',
            field=models.IntegerField(blank=True, help_text='Kommunikation', null=True, verbose_name='communications allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='construction_management_allocation',
            field=models.IntegerField(blank=True, help_text='Bauleitung', null=True, verbose_name='construction management allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='illustrator_allocation',
            field=models.IntegerField(blank=True, help_text='ZeichnerIn', null=True, verbose_name='illustrator allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='overall_pm_team_allocation',
            field=models.IntegerField(blank=True, help_text='Gesamtprojektleitung', null=True, verbose_name='overall pm team allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='planner_control_allocation',
            field=models.IntegerField(blank=True, help_text='Planerleistung', null=True, verbose_name='planner control allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='project_management_allocation',
            field=models.IntegerField(blank=True, help_text='Projektleitung', null=True, verbose_name='project management allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='project_phase',
            field=models.IntegerField(blank=True, help_text='Phase', null=True, verbose_name='project phase'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='project_responsibility',
            field=models.IntegerField(blank=True, help_text='Projektverantwortung', null=True, verbose_name='project responsibility'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='Quartal', max_length=20, null=True, verbose_name='quarter'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='supplementary_construction_management_allocation',
            field=models.IntegerField(blank=True, help_text='Bauleitung (Baubegleitung)', null=True, verbose_name='supplementary construction management allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='total_allocation',
            field=models.IntegerField(blank=True, help_text='Total Aufwand', null=True, verbose_name='total allocation'),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Jahr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_models.Year', verbose_name='year'),
        ),
        migrations.DeleteModel(
            name='QuarterlyDetails',
        ),
    ]
