# Generated by Django 2.0.3 on 2018-05-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0002_auto_20180509_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='year',
            field=models.ForeignKey(help_text='Jahr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_models.Year', verbose_name='year'),
        ),
    ]
