# Generated by Django 2.0.3 on 2018-05-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_data', '0005_auto_20180515_0948'),
        ('helper_models', '0007_auto_20180515_0911'),
        ('project_allocation', '0009_auto_20180515_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectallocation',
            unique_together={('project', 'year', 'quarter')},
        ),
    ]
