# Generated by Django 2.0.3 on 2018-05-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0010_auto_20180515_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectallocation',
            options={'verbose_name': 'Project allocation', 'verbose_name_plural': 'Project allocations'},
        ),
    ]
