# Generated by Django 2.0.3 on 2018-05-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0011_auto_20180515_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectallocation',
            options={'ordering': ['year', 'quarter'], 'verbose_name': 'Project allocation', 'verbose_name_plural': 'Project allocations'},
        ),
    ]
