# Generated by Django 2.0.3 on 2018-05-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_allocation', '0012_auto_20180520_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='project_data.ProjectData', verbose_name='project name'),
        ),
    ]
